name: Github Action Demo
on: push
jobs:
#  run1:
#    name: show node version
#    runs-on: ubuntu-latest
#    steps:
#      - name: print node version
#        run: node -v
#  run2:
#    name: show npm version
#    runs-on: ubuntu-latest
#    needs: run1
#    steps:
#      - name: print npm version
#        run: npm -v
  build:
    name: build action
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: 显示node版本
        run: node -v

      - name: 安装依赖
        run: npm install

      - name: 编译
        run: npm run build

      - name: 复制文件
        run: cp -r dist ~/release/dist

  release:
    name: release action
    runs-on: ubuntu-latest
    steps:
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vue-build
          path: ~/release/dist  # 替换为您编译后的文件所在的路径