name: Github Action Demo
on: push
jobs:
  run1:
    name: show node version
    runs-on: ubuntu-latest
    steps:
      - name: print node version
        run: node -v
  run2:
    name: show npm version
    runs-on: ubuntu-latest
    needs: run1
    steps:
      - name: print npm version
        run: npm -v