name: Github Action Demo
on: push
jobs:
#  run1:
#    name: show node version
#    runs-on: ubuntu-latest
#    steps:
#      - name: print node version
#        run: node -v
#  run2:
#    name: show npm version
#    runs-on: ubuntu-latest
#    needs: run1
#    steps:
#      - name: print npm version
#        run: npm -v
  run3:
    name: 打包
    runs-on: ubuntu-latest
    steps:
      - name: 显示node版本
        run: node -v
      - name: 显示npm版本
        run: npm -v
      - name: 安装依赖
        uses: YongTay/action-demo@main
        run: npm install
      - name: 打包
        uses: YongTay/action-demo@main
        run: npm run build
